config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('crmadmin/', admin.site.urls),
    path('', include('myapp.urls'))
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

myapp/urls.py
from django.urls import path
from .views import CreateViewUser,Index,Congratulations

urlpatterns = [
    path('register/', CreateViewUser.as_view(), name='register'),
    path('', Index.as_view(), name='home'),
    path('congrats/', Congratulations.as_view(), name='congrats'),
]

myapp/models.py
from django.db import models


class Client(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    phone = models.BigIntegerField()

    def __str__(self):
        return f"{self.first_name} {self.last_name}: {self.phone}"

myapp/views.py
from django.views.generic import CreateView, TemplateView
from .models import Client
from django.urls import reverse_lazy


class CreateViewUser(CreateView):
    model = Client
    template_name = 'register.html'
    fields = ['first_name', 'last_name', 'phone']
    success_url = reverse_lazy('congrats')


class Index(TemplateView):
    template_name = 'index.html'


class Congratulations(TemplateView):
    template_name = 'congrats.html'

templates/congrats.html
{% load static %}
<html>
<head>
    <link rel="stylesheet" type="text/css" href="{% static 'css/index.css' %}">
</head>
<body style="background-image: url('{% static 'media/background.png' %}');">
    <p style="position: absolute; top: 35px; left: 160px; color: rgb(44, 156, 248); font-size: 100px;">Tabriklayman</p>
    <p style="color: white; position: absolute; top: 220px; left: 164px; font-size: 25px;">SIZ RO'YXATDAN O'TDINGIZ BEPUL</p>
    <p style="color: white; position: absolute; top: 255px; left: 164px; font-size: 25px;">VEBINARNING HAVOLASINI O'ZIMNING SHAXSIY</p>
    <p style="color: white; position: absolute; top: 290px; left: 164px; font-size: 25px;"><a href="https://t.me/+hpiB-CllEh00ZmMy">TELEGRAM KANALIMDA </a> E'LON QILAMAN</p>
    <p style="color: white; position: absolute; top: 330px; left: 250px; font-size: 40px; font-family: Impact, Haettenschweiler, 'Arial Narrow Bold', sans-serif;">Siz uchun sovg'a bor</p>
    <p style="color: white; position: absolute; top: 550px; left: 200px; font-size: 30px;">TELEGRAMDA RIVOJLANISH YO'LLARI <br> VA DAROMAD USULLARI HAQIDA</p>
    <a href="https://t.me/+W5Q-hmXupPtkMzVi"><button class="qollanma">Qo'llanmani olish</button></a>
    <img src="{% static 'media/telegramlogo.png' %}" alt="Person" style="position: absolute; bottom: 400px; right: 150px; width: 200px; height: 200px;">
    <img src="{% static 'media/robot.png' %}" alt="Person" style="position: absolute; bottom: 400px; right: 350px; width: 200px; height: 200px;">
    <img src="{% static 'media/person.png' %}" alt="Person" style="position: absolute; bottom: 0px; right: 144px; width: 400px; height: 600px;">
</body>
</html>

templates/index.html
{% load static %}

<html>
<head>
<link rel="stylesheet" type="text/css" href="{% static 'css/index.css' %}">
    <meta name="viewport" content="width=device-width, initial">
</head>
<body style="background-image: url('{% static 'media/background.png' %}');">
    <img src="{% static 'media/telegram.png' %}" alt="Telegram Logo" style="position: absolute; top: 17%; left: 10%; width: 45%; height: 18%;">
    <p style="color: white; position: absolute; top: 25%; left: 10%; font-size: 100%;">ORQALI SIFATLI KONTENT</p>
    <p style="color: white; position: absolute; top: 300px; left: 164px; font-size: 50px;">YARATISH VA DAROMADGA</p>
    <p style="color: white; position: absolute; top: 380px; left: 164px; font-size: 50px;">CHIQARISH</p>
    <p style="color: white; position: absolute; top: 460px; left: 250px; font-size: 30px;">BEPUL VEBINAR O'TISH SANASI</p>
    <p style="color: white; position: absolute; top: 500px; left: 390px; font-size: 25px; color:rgb(110, 162, 247);">9-10-NOYABR</p>
    <a href="{% url 'register' %}"> <button class="button">Ro'yxatdan o'tish</button></a>
    <img src="{% static 'media/telegramlogo.png' %}" alt="Telegram Logo" style="position: absolute; bottom: 400px; right: 100px; width: 250px; height: 250px;">
    <img src="{% static 'media/robot.png' %}" alt="Robot" style="position: absolute; bottom: 400px; right: 400px; width: 230px; height: 230px;">
    <img src="{% static 'media/person.png' %}"  alt="Person" style="position: absolute; bottom: 0%; right: 144px; width: 450px; height: 700px;">

</body>
</html>

templates/register.html
{% load static %}
<html lang="en" dir="ltr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static 'css/register.css' %}">
    <title> Registration</title>
    <link rel="stylesheet" href="style.css">
</head>
<body>
<div class="wrapper">
    <h2>Ro'yxatdan o'tish uchun ma'lumotlaringizni kiriting:</h2>
    <form method="POST">
        {% csrf_token %}
        <div class="input-box">
            <input type="text" placeholder="Ism" required name="first_name" id="id_first_name">
        </div>

        <div class="input-box">
            <input type="text" placeholder="Familiya" required name="last_name" id="id_last_name">
        </div>
        <div class="input-box">
            <input type="text" placeholder="Telefon Raqam" value="+998" required name="phone" id="id_phone">
        </div>
        <div class="input-box button">
            <input type="Submit" value="Ro'yxatdan o'tish">
        </div>
    </form>
</div>

</body>
</html>